config/routes.rb
Rails.application.routes.draw do
  resource :home, only: :index
  resources :users, only: [:index, :create] do
    collection do
      get :login
      get :logout
    end
  end
  resources :posts, only: [:index, :create]

  root to: "home#index"
end



# Rails.application.routes.draw do
#   resource :home, only: :index
#   resources :users, only: :create

#   root to: "home#index"
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :password

  validates :email, :password, presence: true
  validates :email, uniqueness: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  protected

  def current_user
    User.find_by(id: session[:current_user_id])
  end

  def authenticate_user
    redirect_to root_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to posts_path if current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user

  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def create
    @post = current_user.posts.create(post_params)

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index, :logout]

  def index
    @users = User.order(created_at: :desc)
  end

  def create
    @user = User.create(user_params)

    session[:current_user_id] = @user.id if @user.persisted?

    respond_to do |format|
      format.turbo_stream
    end
  end

  def login
  end

  def logout
    session[:current_user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="relative isolate overflow-hidden bg-gray-900 py-16 sm:py-24 lg:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2">
      <div class="max-w-xl lg:max-w-lg">
        <h2 class="header-text">Subscribe to Post</h2>
        <p class="header-subtext">Enter your unique email to be able to start posting comments in our platform!</p>

        <turbo-frame id="new-registration-feedback">
        </turbo-frame>

        <div class="mt-6 flex max-w-md gap-x-4">
          <turbo-frame id="new-registration">
            <%= form_with scope: :user, url: users_path do |form| %>
              <%= form.label :email, class: "sr-only" %>
              <%= form.email_field :email, placeholder: "Enter your email", class: "text-input", required: true, autocomplete: "email" %>
              <%= form.label :password, class: "sr-only" %>
              <%= form.password_field :password, placeholder: "Enter your password", class: "text-input", required: true, autocomplete: :password %>
              <%= form.submit 'Subscribe', class: "btn-submit" %>
            <% end %>
          </turbo-frame>
        </div>
      </div>
      <dl class="grid grid-cols-1 gap-x-8 gap-y-10 sm:grid-cols-2 lg:pt-2">
        <div class="flex flex-col items-start">
          <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
            <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M10.05 4.575a1.575 1.575 0 10-3.15 0v3m3.15-3v-1.5a1.575 1.575 0 013.15 0v1.5m-3.15 0l.075 5.925m3.075.75V4.575m0 0a1.575 1.575 0 013.15 0V15M6.9 7.575a1.575 1.575 0 10-3.15 0v8.175a6.75 6.75 0 006.75 6.75h2.018a5.25 5.25 0 003.712-1.538l1.732-1.732a5.25 5.25 0 001.538-3.712l.003-2.024a.668.668 0 01.198-.471 1.575 1.575 0 10-2.228-2.228 3.818 3.818 0 00-1.12 2.687M6.9 7.575V12m6.27 4.318A4.49 4.49 0 0116.35 15m.002 0h-.002" />
            </svg>
          </div>
          <dt class="mt-4 font-semibold text-white">No spam</dt>
          <dd class="mt-2 leading-7 text-gray-400">We do not allow the same posts to be published more than once.</dd>
        </div>
      </dl>
    </div>
  </div>
  <div class="absolute left-1/2 top-0 -z-10 -translate-x-1/2 blur-3xl xl:-top-6" aria-hidden="true">
    <div class="aspect-[1155/678] w-[72.1875rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 text-white p-4 mt-8">
  <div class="max-w-screen-xl mx-auto px-4">
    <div class="flex flex-wrap justify-between items-center">
      <div class="p-4">
        <h2 class="text-lg font-semibold">Brand Name</h2>
        <p class="text-sm">© 2024 Brand Name. All rights reserved.</p>
      </div>
      <div class="p-4">
        <h3 class="text-lg font-semibold">Links</h3>
        <ul class="list-none">
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">Home</a></li>
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">About Us</a></li>
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">Services</a></li>
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">Contact</a></li>
        </ul>
      </div>
      <div class="p-4">
        <h3 class="text-lg font-semibold">Follow Us</h3>
        <ul class="list-none">
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">Twitter</a></li>
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">Facebook</a></li>
          <li><a href="#" class="text-white hover:text-gray-400 text-sm">Instagram</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-gray-200">
  <nav class="mx-auto flex max-w-7xl items-center justify-between py-2 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to image_tag("https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600", class: "h-8 w-auto"), root_path, class: "m-1.5 p-1.5" %>
    </div>
    <div class="flex lg:hidden">
      <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
        <span class="sr-only">Open main menu</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    </div>
    <div class="hidden lg:flex lg:gap-x-12">
      <%= link_to "Users", users_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
      <%= link_to "Posts", posts_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
    </div>
    <% if current_user %>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <%= link_to "Log out", logout_users_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
      </div>
    <% else %>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <%= link_to "Log in", login_users_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
      </div>
    <% end -%>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railshotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <main class="m-1 p-6">
      <%= yield %>
    </main>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="my-2 rounded overflow-hidden shadow-lg bg-white hover:bg-blue-50 transition-colors duration-150 ease-in-out">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2 text-gray-800"><%= post.body %></div>
  </div>
  <div class="px-6 pt-4 pb-2">
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-xs font-semibold text-gray-700 mr-2 mb-2">
      by: <%= post.user.email %>
    </span>
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-xs font-semibold text-gray-700 mr-2 mb-2">
      at: <%= post.created_at %>
    </span>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<% if @post.persisted? %>
  <%= turbo_stream.prepend "posts", partial: "posts/post", locals: { post: @post } %>
<% else %>
  <turbo-stream action="update" target="new-post-feedback">
    <template>
      <div class="error-message bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">
          <%= @post.errors.full_messages.join(", ") %>
        </strong>
      </div>
    </template>
  </turbo-stream>
<% end -%>

app/views/posts/index.html.erb
<turbo-frame id="new-post-feedback">
</turbo-frame>

<div class="flex flex-col items-center">
  <%= form_with scope: :post, url: posts_path, class: "w-1/2" do |form| %>
    <%= form.label :body, class: "sr-only" %>
    <%= form.text_area :body, placeholder: "Enter your text", class: "textarea-input", required: true %>
    <%= form.submit 'Post!', class: "btn-submit" %>
  <% end %>

  <turbo-frame id="posts" class="py-5">
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </turbo-frame>
</div>

app/views/users/create.turbo_stream.erb
<% if @user.persisted? %>
  <turbo-stream action="remove" target="new-registration">
  </turbo-stream>

  <turbo-stream action="replace" target="new-registration-feedback">
    <template>
      <div class="success-message bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">You're registered!</strong>
      </div>
    </template>
  </turbo-stream>
<% else %>
  <turbo-stream action="update" target="new-registration-feedback">
    <template>
      <div class="error-message bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">
          <%= @user.errors.full_messages.join(", ") %>
        </strong>
      </div>
    </template>
  </turbo-stream>
<% end -%>

app/views/users/index.html.erb
<div class="flex flex-wrap justify-center gap-4 p-5">
  <% @users.each do |user| %>
    <div class="max-w-sm rounded overflow-hidden shadow-lg bg-white hover:bg-blue-50 transition-colors duration-150 ease-in-out">
      <div class="px-6 py-4">
        <div class="font-bold text-l mb-2 text-gray-800"><%= user.email %></div>
      </div>
      <div class="px-6 pt-4 pb-2">
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-xs font-semibold text-gray-700 mr-2 mb-2">
          date created: <%= user.created_at %>
        </span>
      </div>
    </div>
  <% end %>
</div>